name: "Manage Heroku Review App"
description: "Creates or Destroy a Review App in Heroku for the current PR"
inputs:
  action:
    description: 'One of: "create" or "destroy"'
    required: true
    default: "create"
runs:
  using: "node12"
  main: "dist/index.js"
